config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :homes, only: [:index] do
    get 'search', on: :collection
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  resources :users, only: [:show] do
    collection do
      get 'mypage'
      get 'edit_password'
      patch 'update_password'
      get 'confirm_withdrawal'
      resource :profile, only: [:edit, :update] do
        delete 'delete_icon', on: :collection
      end
      resources :posts, except: [:index] do
        resource :favorite, only: [:create, :destroy, :show]
        resources :comments, only: [:create, :destroy]
      end
    end

    member do
      get 'favorites'
      get 'follows'
      get 'followers'
    end
    resource :relationships, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 30 }
  validates :url, length: { maximum: 100 }
  validates :description, length: { maximum: 400 }
  validates :address, presence: true

  belongs_to :user

  has_many_attached :pictures

  VALID_PICTURE_TYPES = ['image/jpeg', 'image/jpg', 'image/png'].freeze
  MAX_PICTURE_SIZE = 5.megabytes
  MAX_COUNT_OF_PICTURES = 3

  validate :check_pictures_type
  validate :check_pictures_size
  validate :check_pictures_count

  has_many :posts_members, dependent: :destroy
  has_many :members, through: :posts_members

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited?(user)
    favorites.exists?(user_id: user.id)
  end

  has_many :comments, dependent: :destroy

  private

  def check_pictures_type
    if pictures.attached? && pictures.any? { |picture| !picture.content_type.in?(VALID_PICTURE_TYPES) }
      valid_types = VALID_PICTURE_TYPES.map { |type| type.split('/').last.upcase }
      errors.add(:pictures, "のファイル形式は#{valid_types.join('、')}である必要があります。")
    end
  end

  def check_pictures_size
    if pictures.attached? && pictures.any? { |picture| picture.blob.byte_size > MAX_PICTURE_SIZE }
      errors.add(:pictures, "のファイルサイズは#{MAX_PICTURE_SIZE / 1.megabyte}MB以下である必要があります。")
    end
  end

  def check_pictures_count
    if pictures.attached? && pictures.size > MAX_COUNT_OF_PICTURES
      errors.add(:pictures, "は#{MAX_COUNT_OF_PICTURES}枚までアップロードできます。")
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_without_current_password(user_params)
      flash[:notice] = "プロフィールを更新しました。"
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def delete_icon
    @user = current_user
    @user.icon.purge if @user.icon.attached?
    flash[:notice] = "アイコンを削除しました。"
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :icon, :introduction, member_ids: [])
  end
end

app/views/profiles/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<div class="edit-profile-container container">
  <div class="edit-profile-row row">
    <div class="edit-profile-form col-md-10 col-lg-8 col-xl-8">
      <h3 class="title">プロフィール編集</h3>
      <%= form_with model: @user, url: { controller: 'profiles', action: 'update' }  do |f| %>
        <hr>
        <div class="field-line">
          <div class="field-line-left">
            <%= f.label :icon, "アイコン", for: "img-select-btn" %>
          </div>
          <div class="field-line-right icon-line">
            <% if @user.icon.attached? %>
              <%= image_tag @user.icon, id: "img-prev", class: "rounded-circle", size: "90x90" %>
            <% else %>
              <%= image_tag "default_user.png", id: "img-prev", class: "rounded-circle user-default-img", size: "90x90" %>
            <% end %>
            <span>
              <%= f.file_field :icon, accept: 'image/jpeg, image/jpg, image/png', id: "img-select-btn" %>
              <% if @user.icon.attached? &&  @user.icon != "default_user.png" %>
                <%= link_to "アイコンを削除", delete_icon_profile_path, method: :delete, class: "delete-icon", data: { confirm: "アイコンを削除しますか？" } %>
              <% end %>
            </span>
            <span class="error-message">
              <% if @user.errors.include?(:icon) %>
                <%= @user.errors.full_messages_for(:icon).first %>
              <% end %>
            </span>
          </div>
        </div>
        
        <hr>
        <div class="field-line">
          <div class="field-line-left">
            <%= f.label :username, "ユーザー名" %>
            <span class="comment">（15文字以内）</span>
          </div>
          <div class="field-line-right">
            <%= f.text_field :username, autocomplete: "username" %>
            <span class="error-message">
              <% if @user.errors.include?(:username) %>
                <%= @user.errors.full_messages_for(:username).first %>
              <% end %>
            </span>
          </div>
        </div>
        
        <hr>
        <div class="field-line">
          <div class="field-line-left">
            <%= f.label :introduction, "プロフィール" %>
            <span class="comment">（200文字以内）</span>
          </div>
          <div class="field-line-right">
            <%= f.text_area :introduction %>
            <span class="error-message">
              <% if @user.errors.include?(:introduction) %>
                <%= @user.errors.full_messages_for(:introduction).first %>
              <% end %>
            </span>
          </div>
        </div>

        <hr>
        <div class="field-line">
          <div class="field-line-left">
            <p class="title-oshimem">推しメン</p>
          </div>
          <div class="field-line-right">
            <div class="oshi-field">
              <%= f.collection_check_boxes :member_ids, Member.all, :id, :name, { multiple: true } %>
            </div>
          </div>
        </div>

        <hr>
        <div class="actions update">
          <%= f.submit "更新" %>
        </div>
        <div class="actions">
          <%= link_to "キャンセル", user_path(@user), class: "btn back-button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>