config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :homes, only: [:index] do
    get 'search', on: :collection
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  resources :users, only: [:show] do
    collection do
      get 'mypage'
      get 'edit_password'
      patch 'update_password'
      get 'confirm_withdrawal'
      resource :profile, only: [:edit, :update] do
        delete 'delete_icon', on: :collection
      end
      resources :posts, except: [:index] do
        resource :favorite, only: [:create, :destroy, :show]
        resources :comments, only: [:create, :destroy]
      end
    end

    member do
      get 'favorites'
      get 'follows'
      get 'followers'
    end
    resource :relationships, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable

  def update_without_current_password(params, *options)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
      params.delete(:current_password)
      skip_reconfirmation!
      result = update(params, *options)
    else
      current_password = params.delete(:current_password)
      result = if valid_password?(current_password)
                 skip_reconfirmation!
                 update(params, *options)
               else
                 assign_attributes(params, *options)
                 valid?
                 errors.add(:current_password, current_password.blank? ? :blank : :invalid)
                 false
               end
    end

    clean_up_passwords
    result
  end

  validates :username, presence: true, length: { maximum: 15 }
  validates :introduction, length: { maximum: 200 }

  has_one_attached :icon

  VALID_ICON_TYPES = ['image/jpeg', 'image/jpg', 'image/png'].freeze
  MAX_ICON_SIZE = 1.megabytes

  validate :check_icon_type
  validate :check_icon_size

  has_many :users_members, dependent: :destroy
  has_many :members, through: :users_members

  has_many :posts, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    followers.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    followers.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    following_users.include?(user)
  end

  has_many :comments, dependent: :destroy

  # ゲストユーザー
  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64(12)
      user.password_confirmation = user.password
      user.username = "ゲスト"
      user.confirmed_at = Time.now
    end
  end

  private

  def check_icon_type
    if icon.attached? && !icon.content_type.in?(VALID_ICON_TYPES)
      valid_types = VALID_ICON_TYPES.map { |type| type.split('/').last.upcase }
      errors.add(:icon, "のファイル形式は#{valid_types.join('、')}である必要があります。")
    end
  end

  def check_icon_size
    if icon.attached? && icon.byte_size > MAX_ICON_SIZE
      errors.add(:icon, "のファイルサイズは#{MAX_ICON_SIZE / 1.megabyte}MB以下である必要があります。")
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  protected

  # パスワードリセット後のリダイレクト先
  def after_resetting_password_path_for(resource)
    new_user_session_path
  end

  # ゲストユーザーのパスワード再設定を不可にする
  def ensure_normal_user
    if params[:user][:email].downcase == "guest@example.com"
      redirect_to new_user_session_path, alert: "ゲストユーザーのパスワード再設定はできません。"
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: [:update, :destroy]

  protected

  # パスワードの変更以外で現在のパスワード入力を不要にする
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  # メールアドレス編集後のリダイレクト先
  def after_update_path_for(resource)
    mypage_users_path
  end

  # ゲストユーザーのアカウント更新・削除を不可にする
  def ensure_normal_user
    if resource.email == "guest@example.com"
      if params[:_method] == "delete"
        redirect_to mypage_users_path, alert: "ゲストユーザーは退会できません。"
      else
        redirect_to mypage_users_path, alert: "ゲストユーザーは更新できません。"
      end
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :favorites, :follows, :followers]

  def show
    @user = current_user
    @post_user = User.find(params[:id])
    @posts = @post_user.posts.includes(:members).order(created_at: :desc)
  end

  def favorites
    @user = current_user
    @post_user = User.find(params[:id])
    @favorited_posts = @post_user.favorited_posts.includes(:members, user: { icon_attachment: :blob }).order(created_at: :desc)
  end

  def follows
    @user = current_user
    @post_user = User.find(params[:id])
    @follows = @post_user.following_users.includes(:members, icon_attachment: :blob)
  end

  def followers
    @user = current_user
    @post_user = User.find(params[:id])
    @followers = @post_user.follower_users.includes(:members, icon_attachment: :blob)
  end

  def mypage
    @user = current_user
  end

  def edit_password
    @user = current_user
    @minimum_password_length = Devise.password_length.min
    @maximum_password_length = Devise.password_length.max
  end

  def update_password
    @user = current_user
    @minimum_password_length = Devise.password_length.min
    @maximum_password_length = Devise.password_length.max
    if @user.email == "guest@example.com"
      redirect_to mypage_users_path, alert: "ゲストユーザーは更新できません。"
    else
      if @user.update_with_password(user_params)
        sign_out @user
        flash[:notice] = "パスワードが更新されました。ログアウトしました。"
        redirect_to root_path
      else
        render "edit_password"
      end
    end
  end

  def confirm_withdrawal
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end
end

app/views/users/confirm_withdrawal.html.erb
<% provide(:title, "退会確認") %>
<div class="form-container container">
  <div class="withdrawal-row row">
    <div class="withdrawal-content col-md-10 col-lg-10 col-xl-10">
      <span>
        <h3 class="title">退会</h3>
      </span>
      <p>退会すると、アカウントに関する全ての情報が閲覧できなくなります。</p>
      <p>退会する場合は「退会する」を選択してください。</p>
      <div>
        <%= link_to "MY PAGE", mypage_users_path, class: "btn ms-3 btn-mypage" %>
        <%= link_to "退会する", user_registration_path, method: :delete, class: "btn ms-3 btn-withdrawal", data: { confirm: "本当に退会しますか？" }  %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_password.html.erb
<% provide(:title, "パスワード変更") %>
<div class="form-container container">
  <div class="form-row edit-account-row row">
    <div class="edit-account-form col-md-10 col-lg-8 col-xl-8">
      <%= link_to mypage_users_path, class: "mypage-link" do %>
        <i class="fa-regular fa-circle-left"></i>
        <div>MY PAGE</div>
      <% end %>
      <h3 class="title">パスワード変更</h3>
    </div>

    <div class="edit-account-form col-md-10 col-lg-8 col-xl-8">
      <%= form_with model: @user, url: {controller: 'users', action: 'update_password'} do |f| %>
        <p>パスワードは<%= @minimum_password_length %>文字以上<%= @maximum_password_length %>文字以内で入力してください。</p>

        <div class="field icon-std">
          <%= f.label :current_password, "現在のパスワード" %><br>
          <%= f.password_field :current_password, autocomplete: "current-password", class: "current-password-field" %>
          <span id="current-password-toggle"><i class="fa-solid fa-eye"></i></span>
          <span class="error-message">
            <% if @user.errors.include?(:current_password) %>
              <%= @user.errors.full_messages_for(:current_password).first %>
            <% end %>
          </span>
        </div>

        <div class="field icon-std">
          <%= f.label :password, "新しいパスワード" %><br>
          <%= f.password_field :password, autocomplete: "new-password", class: "password-field", required: true %>
          <span id="password-toggle"><i class="fa-solid fa-eye"></i></span>
          <span class="error-message">
            <% if @user.errors.include?(:password) %>
              <%= @user.errors.full_messages_for(:password).first %>
            <% end %>
          </span>
        </div>

        <div class="field icon-std">
          <%= f.label :password_confirmation, "新しいパスワード（確認）" %><br>
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "password-confirmation-field" %>
          <span id="password-confirmation-toggle"><i class="fa-solid fa-eye"></i></span>
          <span class="error-message">
            <% if @user.errors.include?(:password_confirmation) %>
              <%= @user.errors.full_messages_for(:password_confirmation).first %>
            <% end %>
          </span>
        </div>

        <div class="actions">
          <%= f.submit "更新" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<% provide(:title, "#{@post_user.username}: ユーザー詳細") %>
<div class="notice"><%= notice %></div>
<div class="navigation-link">
  <div>
    <%= link_to_unless_current "TOP", root_path, data: { "turbolinks" => false } %>
    <i class="fa-solid fa-angle-right fa-xs" style="color: #ffffff; margin: 0 2px;"></i>
    <%= link_to_unless_current @post_user.username, user_path(@post_user), data: { "turbolinks" => false } %>
  </div>
</div>
<div class="top flex-shrink-0 user-info-container">
  <%= render "shared/profile", user: @post_user %>
  <div class="posts-area">
    <span>
      <h1 class="title">
        <span>
          <i class="fa-solid fa-heart"></i>
          <span>MY FAVORITES</span>
        </span>
        <%= link_to "マイ投稿一覧", user_path(@post_user), class: "favorites-btn btn" %>
      </h1>
      <%= render "shared/posts", posts: @favorited_posts, user: @user %>
    </span>
  </div>
</div>

app/views/users/followers.html.erb
<% provide(:title, "#{@post_user.username}: フォロワー") %>
<div class="navigation-link">
  <div>
    <%= link_to_unless_current "TOP", root_path, data: { "turbolinks" => false } %>
    <i class="fa-solid fa-angle-right fa-xs" style="color: #ffffff; margin: 0 2px;"></i>
    <%= link_to_unless_current @post_user.username, user_path(@post_user), data: { "turbolinks" => false } %>
    <i class="fa-solid fa-angle-right fa-xs" style="color: #ffffff; margin: 0 2px;"></i>
    <%= link_to_unless_current "フォロワー", followers_user_path(@post_user), data: { "turbolinks" => false } %>
  </div>
</div>
<div class="flex-shrink-0 users-container">
  <div class="profile-area">
    <h3 class="title">
      <i class="fa-solid fa-users"></i>
      <span>フォロワー</span>
    </h3>
    <% if @followers.present? %>
      <%= render "shared/user_lists", users: @followers %>
    <% else %>
      <div class="not-applicable">フォロワーを獲得しましょう。</div>
    <% end %>
  </div>
</div>

app/views/users/follows.html.erb
<% provide(:title, "#{@post_user.username}: フォロー") %>
<div class="navigation-link">
  <div>
    <%= link_to_unless_current "TOP", root_path, data: { "turbolinks" => false } %>
    <i class="fa-solid fa-angle-right fa-xs" style="color: #ffffff; margin: 0 2px;"></i>
    <%= link_to_unless_current @post_user.username, user_path(@post_user), data: { "turbolinks" => false } %>
    <i class="fa-solid fa-angle-right fa-xs" style="color: #ffffff; margin: 0 2px;"></i>
    <%= link_to_unless_current "フォロー", follows_user_path(@post_user), data: { "turbolinks" => false } %>
  </div>
</div>
<div class="flex-shrink-0 users-container">
  <div class="profile-area">
    <h3 class="title">
      <i class="fa-solid fa-users"></i>
      <span>フォロー</span>
    </h3>
    <% if @follows.present? %>
      <%= render "shared/user_lists", users: @follows %>
    <% else %>
      <div class="not-applicable">フォローしたユーザーはいません。</div>
    <% end %>
  </div>
</div>

app/views/users/mypage.html.erb
<% provide(:title, "マイページ") %>
<div class="notice"><%= notice %></div>
<div class="alert"><%= alert %></div>
<div class="mypage-container container">
  <div class="mypage-row row">
    <h1 class="title">MY PAGE</h1>
    <div>
      <div class="subtitle">プロフィール</div>
      <hr>
      <div class="profile-area">
        <div class="profile-area-top">
          <div>
            <% if @user.icon.attached? %>
              <%= image_tag @user.icon, class:"rounded-circle", size: "70x70" %>
            <% else %>
              <%= image_tag "default_user.png", class:"rounded-circle user-default-img", size: "70x70" %>
            <% end %>
          </div>
          <%= link_to user_path(@user), class: "link-field-profile", data: { "turbolinks" => false } do %>
            <i class="fa-regular fa-user"></i>
            <p>詳細</p>
          <% end %>
        </div>
        <h4 class="profile-area-username"><%= @user.username %></h4>
        <div class="profile-area-middle">
          <div class="profile-area-ff">
            <%= link_to "#{@user.following_users.count}フォロー", follows_user_path(@user), class: "ff-link" %>
            <%= link_to "#{@user.follower_users.count}フォロワー", followers_user_path(@user), class: "ff-link" %>
          </div>
        </div>
        <div class="profile-area-introduction">
          <p><%= @user.introduction %></p>
        </div>
        <div class="profile-area-oshi">
          <span>
            <p>推しメン</p>
            <% if @user.members.empty? %>
              <div class="oshi-none">未設定</div>
            <% end %>
          </span>
          <% @user.members.each do |member| %>
            <div class="oshi"><%= member.name %></div>
          <% end %>
        </div>
      </div>
    </div>
    <div>
      <div class="subtitle">アカウント</div>
      <hr>
      <ul>
        <li>
          <%= link_to edit_user_registration_path, class: "link-field" do %>
            <p>メールアドレス</p>
            <div class="link-field-email">
              <span><%= @user.email %></span>
              <i class="fa-solid fa-angle-right"></i>
            </div>
          <% end %>
        </li>
        <li>
          <%= link_to edit_password_users_path, class: "link-field" do %>
            <p>パスワード</p>
            <i class="fa-solid fa-angle-right"></i>
          <% end %>
        </li>
      </ul>
    </div>
    <div>
      <div class="subtitle">その他</div>
      <hr>
      <ul>
        <li>
          <%= link_to confirm_withdrawal_users_path, class: "link-field" do %>
            <p>退会</p>
            <i class="fa-solid fa-angle-right"></i>
          <% end %>
        </li>
      </ul>
    </div>
    <div>
      <hr>
      <ul>
        <li>
          <%= link_to destroy_user_session_path, method: :delete, class: "link-field" do %>
            <p>ログアウト</p>
            <i class="fa-solid fa-angle-right"></i>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@post_user.username}: ユーザー詳細") %>
<div class="notice"><%= notice %></div>
<div class="navigation-link">
  <div>
    <%= link_to_unless_current "TOP", root_path, data: { "turbolinks" => false } %>
    <i class="fa-solid fa-angle-right fa-xs" style="color: #ffffff; margin: 0 2px;"></i>
    <%= link_to_unless_current @post_user.username, user_path(@post_user), data: { "turbolinks" => false } %>
  </div>
</div>
<div class="top flex-shrink-0 user-info-container">
  <%= render "shared/profile", user: @post_user %>
  <div class="posts-area">
    <span>
      <h1 class="title">
        <span>
          <i class="fa-solid fa-map-pin"></i>
          <span>MY POSTS</span>
        </span>
        <%= link_to "いいね一覧", favorites_user_path(@post_user), class: "favorites-btn btn" %>
      </h1>
      <%= render "shared/posts", posts: @posts, user: @user %>
    </span>
  </div>
</div>