config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :homes, only: [:index] do
    get 'search', on: :collection
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  resources :users, only: [:show] do
    collection do
      get 'mypage'
      get 'edit_password'
      patch 'update_password'
      get 'confirm_withdrawal'
      resource :profile, only: [:edit, :update] do
        delete 'delete_icon', on: :collection
      end
      resources :posts, except: [:index] do
        resource :favorite, only: [:create, :destroy, :show]
        resources :comments, only: [:create, :destroy]
      end
    end

    member do
      get 'favorites'
      get 'follows'
      get 'followers'
    end
    resource :relationships, only: [:create, :destroy]
  end
end

app/views/shared/_after_liked.html.erb
<%= link_to post_favorite_path(post.id), class: "filled-heart", method: :delete, remote: true do %>
  <i class="fa-solid fa-heart"></i>
<% end %>
<%= link_to post.favorites.size, post_favorite_path(post), class: "likes" %>

app/views/shared/_before_liked.html.erb
<%= link_to post_favorite_path(post.id), class: "heart", method: :post, remote: true do %>
  <i class="fa-regular fa-heart"></i>
<% end %>
<%= link_to post.favorites.size, post_favorite_path(post), class: "likes" %>

app/views/shared/_comment_count.html.erb
<span>レビュー <%= comments.count %>件</span>
<% if comments.average(:rate).present? %>
  <span class="average-rate">
    （ 評価: <span class="star5-average-rating" data-rate="<%= number_with_precision(comments.average(:rate), precision: 1) %>"></span><span><%= number_with_precision(comments.average(:rate), precision: 1) %></span> ）
  </span>
<% end %>

app/views/shared/_comment_form.html.erb
<%= form_with model: [post, comment], local: false do |f| %>
  <div>レビューを書く</div>
  <div>
    <div class="field">
      <%= f.radio_button :rate, 5, id: "star1" %>
      <label for="star1"><span class="text">最高</span>★</label>
      <%= f.radio_button :rate, 4, id: "star2" %>
      <label for="star2"><span class="text">良い</span>★</label>
      <%= f.radio_button :rate, 3, id: "star3" %>
      <label for="star3"><span class="text">普通</span>★</label>
      <%= f.radio_button :rate, 2, id: "star4" %>
      <label for="star4"><span class="text">悪い</span>★</label>
      <%= f.radio_button :rate, 1, id: "star5" %>
      <label for="star5"><span class="text">最低</span>★</label>
    </div>
    <div class="field"><%= f.text_area :comment, id: "comment-textarea", placeholder: "レビューを記入" %></div>
    <%= f.hidden_field :user_id, value: user.id if user_signed_in? %>
    <div class="actions"><%= f.submit "レビューする" %></div>
  </div>
<% end %>

app/views/shared/_comments.html.erb
<% comments.each do |comment| %>
  <div class="comment">
    <div>
      <div class="created-at"><%= comment.created_at.strftime("%Y年%m月%d日 %H:%M") %></div>
      <% if comment.user == current_user %>
        <%= link_to post_comment_path(post, comment), method: :delete, class: "trash-can", data: { confirm: "レビューを削除しますか？" }, remote: true do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      <% end %>
    </div>
    <%= link_to user_path(comment.user) do %>
      <% if comment.user.icon.attached? %>
        <%= image_tag comment.user.icon, class:"rounded-circle", size: "35x35" %>
      <% else %>
        <%= image_tag "default_user.png", class:"rounded-circle user-default-img", size: "35x35" %>
      <% end %>
      <div class="username"><%= comment.user.username %></div>
    <% end %>
    <div>
      <div class="star5-rating">
        <span class="star5-rating-front" style="width: <%= get_percent(comment.rate) %>%;">★★★★★</span>
        <span class="star5-rating-back">★★★★★</span>
      </div>
    </div>
    <div class="body"><%= comment.comment %></div>
  </div>
<% end %>

app/views/shared/_follow_btn.html.erb
<% if current_user && current_user.following?(user) %>
  <%= link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "btn btn-unfollow", remote: true %>
<% else %>
  <%= link_to "フォロー", user_relationships_path(user.id), method: :post, class:"btn btn-follow", remote: true %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div>
    <div class="logo">
      <%= link_to root_path, class: "navbar-brand", data: { "turbolinks" => false } do %>
        <%= image_tag "OSHIDOKO_removebg.png", size: "195x55" %>
      <% end %>
    </div>
    <div class="copyright">
      <div>&copy; 2016 Seed & Flower LLC&emsp;当ウェブサイトで使用しているマーカー画像の著作権、商標権、およびその他知的財産権は、当該コンテンツの提供元に帰属します。</div>
      <div>&copy; 2023 Reo Kambara</div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-md inner fixed-top">
    <div class="container-fluid">
      <div class="header-left">
        <%= link_to root_path, class: "navbar-brand", data: { "turbolinks" => false } do %>
          <%= image_tag "OSHIDOKO.png", size: "150x45" %>
        <% end %>
      </div>
      <div class="header-right">
        <div class="collapse navbar-collapse nav-items" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "TOP", root_path, class: "nav-link active top-link", "aria-current": "page", data: { "turbolinks" => false } %></li>
            <li class="nav-item"><%= link_to "MAP", root_path(anchor: "map-anchor"), class: "nav-link", data: { "turbolinks" => false } %></li>
            <li class="nav-item"><%= link_to "POSTS", root_path(anchor: "posts-anchor"), class: "nav-link", data: { "turbolinks" => false } %></li>
            <li class="nav-item"><%= link_to "CONTACT", new_contact_path, class: "nav-link" %></li>
          </ul>
        </div>
        <div class="btn-account">
          <% if user_signed_in? %>
            <span class="status-signed-in">
              <%= link_to mypage_users_path do %>
                <span class="header-icon">
                  <% if @user.icon.attached? %>
                    <%= image_tag @user.icon, class: "rounded-circle", size: "40x40" %>
                  <% else %>
                    <%= image_tag "default_user.png", class: "rounded-circle user-default-img", size: "40x40" %>
                  <% end %>
                </span>
                <span class="header-username">
                  <%= @user.username %>
                </span>
              <% end %>
            </span>
          <% else %>
            <span class="status-signed-out">
              <%= link_to "ログイン", new_user_session_path %>
              <%= link_to "新規登録", new_user_registration_path %>
            </span>
          <% end %>
        </div>
        <div class="btn-group header-menu">
          <button type="button" class="btn btn-sm" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-custom">
            <% unless user_signed_in? %>
              <li class="dropdown-item top-link hidden-over-435px"><%= link_to "ログイン", new_user_session_path %></li>
              <li class="dropdown-item top-link hidden-over-435px"><%= link_to "新規登録", new_user_registration_path %></li>
              <li><hr class="dropdown-divider hidden-over-435px"></li>
            <% end %>
            <li><%= link_to "TOP", root_path, class: "dropdown-item top-link", data: { "turbolinks" => false } %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "MAP", root_path(anchor: "map-anchor"), class: "dropdown-item", data: { "turbolinks" => false } %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "POSTS", root_path(anchor: "posts-anchor"), class: "dropdown-item", data: { "turbolinks" => false } %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "CONTACT", new_contact_path, class: "dropdown-item" %></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_posts.html.erb
<div class="posts">
  <div class="number-of-displays"><%= posts.count %>件</div>
  <% posts.each do |post| %>
    <div class="post">
      <span class="hidden-over-767px post-upper my-post-upper">
        <div class="post-created-at"><%= post.created_at.strftime("%Y年%m月%d日 %H:%M") %></div>
        <div class="links">
          <div class="positive-link">
            <%= link_to post_path(post), class: "info-link", data: { "turbolinks" => false } do %><i class="fa-solid fa-circle-info"></i><% end %>
          </div>
          <% if user == post.user %>
            <div class="positive-link">
              <%= link_to edit_post_path(post), class: "edit-link", data: { "turbolinks" => false } do %><i class="fa-regular fa-pen-to-square"></i><% end %>
            </div>
            <div class="negative-link">
              <%= link_to post_path(post), method: :delete, class: "delete-link", data: { confirm: "投稿を削除しますか？" } do %><i class="fa-solid fa-trash"></i><% end %>
            </div>
          <% end %>
        </div>
      </span>
      <div class="post-left">
        <div class="post-left-upper">
          <div>
            <% if post.user.icon.attached? %>
              <%= image_tag post.user.icon, class:"rounded-circle", size: "50x50" %>
            <% else %>
              <%= image_tag "default_user.png", class:"rounded-circle user-default-img", size: "50x50" %>
            <% end %>
          </div>
          <div>
            <span class="hidden-over-767px">
              <% if post.user.icon.attached? %>
                <%= image_tag post.user.icon, class:"rounded-circle", size: "35x35" %>
              <% else %>
                <%= image_tag "default_user.png", class:"rounded-circle user-default-img", size: "35x35" %>
              <% end %>
            </span>
            <%= link_to post.user.username, user_path(post.user), class: "username" %>
            <div>
              <div><%= link_to post.title, post_path(post), class: "title", data: { "turbolinks" => false } %></div>
              <div class="address"><%= post.address %></div>
            </div>
          </div>
        </div>
        <div class="post-left-lower">
          <% unless post.members.empty? %>
            <div class="members-involved">
              <i class="fa-solid fa-person-dress"></i>
              関連メンバー
            </div>
            <div>
              <% post.members.each do |member| %>
                <span class="member-name"><%= member.name %></span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="post-right">
        <div class="post-created-at"><%= post.created_at.strftime("%Y年%m月%d日 %H:%M") %></div>
        <div class="links">
          <div class="positive-link">
            <%= link_to post_path(post), class: "info-link", data: { "turbolinks" => false } do %>
              <i class="fa-solid fa-circle-info"></i>
              詳細
            <% end %>
          </div>
          <% if user == post.user %>
            <div class="positive-link">
              <%= link_to edit_post_path(post), class: "edit-link", data: { "turbolinks" => false } do %>
                <i class="fa-regular fa-pen-to-square"></i>
                編集
              <% end %>
            </div>
            <div class="negative-link">
              <%= link_to post_path(post), method: :delete, class: "delete-link", data: { confirm: "投稿を削除しますか？" } do %>
                <i class="fa-solid fa-trash"></i>
                削除
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="favorite" id="favorite-post-<%= post.id %>">
      <% if user_signed_in? && post.favorited?(@user) %>
        <%= render "shared/after_liked", post: post %>
      <% else %>
        <%= render "shared/before_liked", post: post %>
      <% end %>
    </div>
  <% end %>
</div>
<hr class="end-line">

app/views/shared/_profile.html.erb
<div class="profile-area">
  <h1 class="title">
    <i class="fa-regular fa-id-card"></i>
    <span>PROFILE</span>
  </h1>
  <div class="content">
    <div class="profile-area-top">
      <div>
        <% if user.icon.attached? %>
          <%= image_tag user.icon, class:"rounded-circle", size: "70x70" %>
        <% else %>
          <%= image_tag "default_user.png", class:"rounded-circle user-default-img", size: "70x70" %>
        <% end %>
      </div>
      <% if @user == user %>
        <%= link_to edit_profile_path, class: "link-field-profile", data: { "turbolinks" => false } do %>
          <i class="fa-solid fa-pen" style="color: #22699c;"></i>
          <p class="hidden-within-767px">プロフィール編集</p>
        <% end %>
      <% else %>
        <div id="follow-<%= user.id %>">
          <%= render "shared/follow_btn", user: user %>
        </div>
      <% end %>
    </div>
    <h4 class="profile-area-username"><%= user.username %></h4>
    <div class="profile-area-middle">
      <div class="profile-area-ff">
        <%= link_to "#{user.following_users.count}フォロー", follows_user_path(user), class: "ff-link" %>
        <%= link_to "#{user.follower_users.count}フォロワー", followers_user_path(user), class: "ff-link", id: "follower-link" %>
      </div>
    </div>
    <div class="profile-area-introduction">
      <p><%= user.introduction %></p>
    </div>
    <div class="profile-area-oshi">
      <span>
        <p>推しメン</p>
        <% if user.members.empty? %>
          <div class="oshi-none">未設定</div>
        <% end %>
      </span>
      <% user.members.each do |member| %>
        <div class="oshi"><%= member.name %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_user_lists.html.erb
<div class="content">
  <% users.each do |user| %>
    <div class="user">
      <div class="profile-area-top">
        <div>
          <%= link_to user_path(user) do %>
            <% if user.icon.attached? %>
              <%= image_tag user.icon, class:"rounded-circle", size: "45x45" %>
            <% else %>
              <%= image_tag "default_user.png", class:"rounded-circle user-default-img", size: "45x45" %>
            <% end %>
          <% end %>
          <div>
            <%= link_to user.username, user_path(user), class: "username" %>
            <div class="posts-count">投稿数 <%= user.posts.count %></div>
          </div>
        </div>
        <div>
          <% if @user != user %>
            <div id="follow-<%= user.id %>">
              <%= render "shared/follow_btn", user: user %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="profile-area-oshi">
        <span>
          <p>推しメン</p>
          <% if user.members.empty? %>
            <div class="oshi-none">未設定</div>
          <% else %>
            <div>
              <% user.members.each do |member| %>
                <div class="oshi"><%= member.name %></div>
              <% end %>
            </div>
          <% end %>
        </span>
      </div>
    </div>
  <% end %>
</div>