config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources :homes, only: [:index] do
    get 'search', on: :collection
  end
  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }
  resources :users, only: [:show] do
    collection do
      get 'mypage'
      get 'edit_password'
      patch 'update_password'
      get 'confirm_withdrawal'
      resource :profile, only: [:edit, :update] do
        delete 'delete_icon', on: :collection
      end
      resources :posts, except: [:index] do
        resource :favorite, only: [:create, :destroy, :show]
        resources :comments, only: [:create, :destroy]
      end
    end

    member do
      get 'favorites'
      get 'follows'
      get 'followers'
    end
    resource :relationships, only: [:create, :destroy]
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 30 }, format: { with: VALID_EMAIL_REGEX }
  validates :content, presence: true, length: { maximum: 800 }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @user = current_user
    @contact = Contact.new
  end

  def confirm
    @user = current_user
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render "new"
    end
  end

  def back
    @user = current_user
    @contact = Contact.new(contact_params)
    render "new"
  end

  def create
    @user = current_user
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver_now
      redirect_to done_contacts_path
    else
      render "new"
    end
  end

  def done
    @user = current_user
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/views/contacts/confirm.html.erb
<% provide(:title, "お問い合わせフォーム") %>
<div class="contact-form-container container">
  <div class="contact-form-row row">
    <h3>お問い合わせフォーム</h3>
    <div class="form-status">
      <div>入力</div>
      <div class="current-page">確認</div>
      <div>完了</div>
    </div>

    <div class="contact-form col-md-10 col-lg-8">
      <table>
        <tbody>
          <tr>
            <td class="line-left">お名前</td>
            <td class="line-right"><%= @contact.name %></td>
          </tr>
          <tr>
            <td class="line-left">メールアドレス</td>
            <td class="line-right"><%= @contact.email %></td>
          </tr>
          <tr>
            <td class="line-left">お問い合わせ内容</td>
            <td class="line-right"><%= @contact.content %></td>
          </tr>
        </tbody>
      </table>

      <%= form_with model: @contact do |f| %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :content %>
        <div class="actions-in-confirm positive"><%= f.submit "送信する" %></div>
      <% end %>

      <%= form_with model: @contact, url: back_contacts_path do |f| %>
        <%= f.hidden_field :name %>
        <%= f.hidden_field :email %>
        <%= f.hidden_field :content %>
        <div class="actions-in-confirm negative"><%= f.submit "入力画面に戻る" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/done.html.erb
<% provide(:title, "お問い合わせフォーム") %>
<div class="contact-form-container container">
  <div class="contact-form-row row">
    <h3>お問い合わせフォーム</h3>
    <div class="form-status">
      <div>入力</div>
      <div>確認</div>
      <div class="current-page">完了</div>
    </div>

    <div class="contact-form message col-md-10 col-lg-8">
      <div>送信しました。<span>お問い合わせありがとうございます。</span></div>
      <div><%= link_to "TOPに戻る", root_path, class: "top-link", data: { "turbolinks" => false } %></div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<% provide(:title, "お問い合わせフォーム") %>
<div class="contact-form-container container">
  <div class="contact-form-row row">
    <h3>お問い合わせフォーム</h3>
    <div class="form-status">
      <div class="current-page">入力</div>
      <div>確認</div>
      <div>完了</div>
    </div>

    <div class="sign-up-form col-md-10 col-lg-8">
      <%= form_with model: @contact, url: confirm_contacts_path do |f| %>
        <div class="field required">
          <%= f.label :name, "お名前 （20文字以内）" %><br>
          <%= f.text_field :name, autofocus: true, placeholder: "お名前を入力" %><br>
          <span class="error-message">
            <% if @contact.errors.include?(:name) %>
              <%= @contact.errors.full_messages_for(:name).first %>
            <% end %>
          </span>
        </div>

        <div class="field required">
          <%= f.label :email, "メールアドレス" %><br>
          <%= f.email_field :email, placeholder: "メールアドレスを入力", autocomplete: "email" %><br>
          <span class="error-message">
            <% if @contact.errors.include?(:email) %>
              <%= @contact.errors.full_messages_for(:email).first %>
            <% end %>
          </span>
        </div>

        <div class="field required">
          <%= f.label :content, "お問い合わせ内容 （800文字以内）" %><br>
          <%= f.text_area :content, placeholder: "お問い合わせ内容を入力" %><br>
          <span class="error-message">
            <% if @contact.errors.include?(:content) %>
              <%= @contact.errors.full_messages_for(:content).first %>
            <% end %>
          </span>
        </div>

        <div class="actions">
          <%= f.submit '入力内容の確認' %>
        </div>
      <% end %>
    </div>
  </div>
</div>